create table if not exists public."Portfolios" (
  id bigint generated by default as identity primary key,
  name text not null unique,
  t0_cash double precision not null default 0,
  t2_cash double precision not null default 0,
  initial_cash double precision not null default 0,
  nav_dirty_from_date text
);

create table if not exists public."Trades" (
  id bigint generated by default as identity primary key,
  portfolio_id bigint not null references public."Portfolios"(id) on delete cascade,
  date text not null,
  stock_id text not null,
  action text not null,
  price double precision not null,
  shares integer not null,
  is_disposed boolean not null default false,
  basic_check boolean not null default false,
  tech_check boolean not null default false,
  chips_check boolean not null default false,
  industry_check boolean not null default false,
  trading_notes text,
  settled integer not null default 0,
  technical_score integer not null default 3,
  chip_score integer not null default 3,
  theme_score integer not null default 3,
  take_profit_price double precision,
  stop_loss_price double precision
);

alter table public."Trades"
  add column if not exists take_profit_price double precision;

alter table public."Trades"
  add column if not exists stop_loss_price double precision;

create index if not exists trades_portfolio_date_idx
  on public."Trades" (portfolio_id, date, id);

create index if not exists trades_portfolio_stock_idx
  on public."Trades" (portfolio_id, stock_id);

create table if not exists public."CashFlows" (
  id bigint generated by default as identity primary key,
  portfolio_id bigint not null references public."Portfolios"(id) on delete cascade,
  date text not null,
  type text not null,
  amount double precision not null
);

create index if not exists cashflows_portfolio_date_idx
  on public."CashFlows" (portfolio_id, date, id);

create table if not exists public."MacroJournals" (
  id bigint generated by default as identity primary key,
  date text not null unique,
  content text not null
);

create table if not exists public."StockNames" (
  stock_id text primary key,
  name text not null,
  full_symbol text
);

create table if not exists public."MarketHolidays" (
  date text primary key,
  reason text,
  is_settlement_open boolean not null default false
);

alter table public."MarketHolidays"
  add column if not exists is_settlement_open boolean not null default false;

create table if not exists public."ManualPriceOverrides" (
  stock_id text primary key,
  price double precision not null,
  updated_at text not null
);

create table if not exists public."PriceSnapshots" (
  date text not null,
  stock_id text not null,
  close_price double precision not null,
  source text not null,
  updated_at text not null,
  primary key (date, stock_id)
);

create index if not exists price_snapshots_stock_date_idx
  on public."PriceSnapshots" (stock_id, date);

create table if not exists public."DailyNavSnapshots" (
  portfolio_id bigint not null references public."Portfolios"(id) on delete cascade,
  date text not null,
  nav double precision not null,
  cash double precision not null,
  holdings_value double precision not null,
  cash_flow double precision not null,
  daily_return double precision not null,
  twr double precision not null,
  benchmark_price double precision not null,
  benchmark_daily_return double precision not null,
  benchmark_cum_return double precision not null,
  daily_alpha double precision not null,
  cum_alpha double precision not null,
  drawdown double precision not null,
  notes text,
  allocation_json text,
  is_trading_day integer not null default 1,
  win_flag text,
  updated_at text not null,
  primary key (portfolio_id, date)
);

create index if not exists daily_nav_portfolio_date_idx
  on public."DailyNavSnapshots" (portfolio_id, date);

create table if not exists public."TradeCycleReviews" (
  portfolio_id bigint not null references public."Portfolios"(id) on delete cascade,
  stock_id text not null,
  cycle_no integer not null,
  review_text text,
  updated_at text not null,
  primary key (portfolio_id, stock_id, cycle_no)
);

create index if not exists trade_cycle_reviews_portfolio_stock_idx
  on public."TradeCycleReviews" (portfolio_id, stock_id, cycle_no);

create table if not exists public."NotebookArticles" (
  id bigint generated by default as identity primary key,
  note_type text not null,
  title text not null,
  content text not null,
  created_date text not null,
  update_log_json text not null default '[]',
  updated_at text not null
);

create index if not exists notebook_articles_type_updated_idx
  on public."NotebookArticles" (note_type, updated_at desc, id desc);

insert into public."Portfolios" (name, t0_cash, t2_cash, initial_cash)
values
  ('自己', 1000000, 1000000, 1000000),
  ('爸爸', 500000, 500000, 500000)
on conflict (name) do nothing;

insert into public."MarketHolidays" (date, reason, is_settlement_open)
values
  ('2026-04-03', '兒童節及民族掃墓節連假', false),
  ('2026-04-06', '兒童節及民族掃墓節補假', false),
  ('2026-05-01', '勞動節', false)
on conflict (date) do nothing;
